project:
  type: website
  output-dir: docs

website:
  google-analytics: "G-MZCXLHBTFW"
  title: ""
  navbar:
    left:
      - href: page1.qmd
        text: Início
      - href: page2.qmd
        text: Aplicações e Trabalhos
      - href: blog.qmd
        text: Blog
      - href: conte.qmd
        text: Conte-me mais!
      - href: page3.qmd
        text: Sobre
      - href: page4.qmd
        text: Contato          
format:
  html:
    lang: pt
    theme: darkly
    css: styles.css
    toc: true

